SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `fb_conn_data` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `fb_conn_data`;

CREATE TABLE `dataVals` (
  `valDate` datetime NOT NULL,
  `valUptime` bigint(20) NOT NULL,
  `valBytesSent` bigint(20) NOT NULL,
  `valBytesReceived` bigint(20) NOT NULL,
  `valUpstreamBitRate` bigint(20) NOT NULL,
  `valDownstreamBitRate` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `dataVals`
  ADD PRIMARY KEY (`valDate`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
